openapi: "3.0.3"
info:
  title: OpenAPI - Log BDE
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: http://localhost:8080
  - url: https://log.ceten.fr/api
paths:
  /health:
    get:
      responses:
        "200":
          description: "Health check"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      security: []
      responses:
        "200":
          description: >
            Successfully authenticated.
            The session ID is returned in a cookie named `JSESSIONID`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: CETEN=abcde12345; Path=/; HttpOnly

        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      security: []
      responses:
        "200":
          description: "Register"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: "Account created"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Email already used"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /permanences:
    get:
      security:
        - BDE: []
      responses:
        "200":
          description: "Permanences liste"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Permanence"
  /permanence/{userId}:
    get:
      security:
        - BDE: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: "User ID"
      responses:
        "200":
          description: "Permanences liste"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Permanence"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /permanence/{date}:
    get:
      security:
        - BDE: []
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
          description: "Date"
      responses:
        "200":
          description: "Permanence"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Permanence"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /permanence:
    post:
      security:
        - BDE: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permanence"
      responses:
        "200":
          description: "Permanence created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
    patch:
      security:
        - BDE: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permanence"
      responses:
        "200":
          description: "Permanence updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /documents/noteDeFrais:
    post:
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NoteDeFrais"
      responses:
        "200":
          description: "Note de frais created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
                
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /documents/locationPerso:
    get:
      security:
        - BDE: []
      responses:
        "200":
          description: "Location perso liste"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LocationPerso"
    post:
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationPerso"
      responses:
        "200":
          description: "Location created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationPerso"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /documents/locationAsso:
    get:
      security:
        - BDE: []
      responses:
        "200":
          description: "Location perso liste"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LocationAsso"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
    post:
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationAsso"
      responses:
        "200":
          description: "Location created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationAsso"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /documents/locationPerso/{id}:
    get:
      security:
        - BDE: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: "Location ID"
      responses:
        "200":
          description: "Location"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationPerso"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
    delete:
      security:
        - BDE: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: "Location ID"
      responses:
        "200":
          description: "Location deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /documents/locationAsso/{id}:
    get:
      security:
        - BDE: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: "Location ID"
      responses:
        "200":
          description: "Location"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationAsso"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
    delete:
      security:
        - BDE: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: "Location ID"
      responses:
        "200":
          description: "Location deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "403":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: "Error 500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

components:
  securitySchemes:
    Ceten:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BDE:
      type: http
      scheme: bearer
      bearerFormat: JWT
    Admin:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # base types
    Health:
      type: object
      required:
        - status
        - nb
      properties:
        status:
          type: string
          example: "ok"
        nb:
          type: integer
          example: 1
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: "jean.michel@telecomnancy.net"
        password:
          type: string
          example: "password"
    Message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Error message"
    Permanence:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: "2021-03-01"
    Permanences:
      type: array
      items:
        $ref: "#/components/schemas/Permanence"
    NoteDeFrais:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: "2021-03-01"
        amount:
          type: number
          example: 12.34
        description:
          type: string
          example: "Description"
    LocationPerso:
      type: object
      properties:
        id:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: "2021-03-01"
        description:
          type: string
          example: "Location description"
    LocationAsso:
      type: object
      properties:
        id:
          type: integer
          example: 1
        date:
          type: string
          format: date
          example: "2021-03-01"
        description:
          type: string
          example: "Location description"
