openapi: "3.0.3"
info:
  title: OpenAPI - Log BDE
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: http://localhost:8080
  - url: https://log-ceten.work.gd/api
paths:
  /health:
    get:
      responses: 
        '200':
          description: "Health check"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
components:
  schemas:
    # base types
    HealthCheck:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          example: "ok"
