# https://taskfile.dev

version: '3'

tasks:
  setup: 
    cmds:
      - go mod download
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install github.com/fatih/gomodifytags@latest
  regen:
    cmds:
      - oapi-codegen -generate="types,server,strict-server,spec" -package autogen log.openapi.yml > autogen/log.gen.go
      - go mod tidy
      - gomodifytags -all -file autogen/log.gen.go -add-tags bson -w > /dev/null